# Generated by Django 5.1.6 on 2025-02-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
